version: '3.8'

services:
  go:
    container_name: go
    build:
      context: ./golang
      dockerfile: Dockerfile
    tty: true
    ports:
      - 8080:8080
    env_file:
      - ./mysql/.env
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./golang/src
        target: /go/src
    networks:
      - go_sample_network

  db:
    container_name: db
    image: mysql:8.0
    ports:
      - 3306:3306
    env_file:
      - ./mysql/.env
    volumes:
      - mysql_test_volume:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    networks:
      - go_sample_network

volumes:
  mysql_test_volume:
    name: mysql_test_volume

networks:
  go_sample_network:
    external: true
